language: node_js
node_js:
  - 12
services:
  - docker

# Pre-testing installs
install:
  - echo "nothing need to be installed"

# Scripts to run before script, ex: tests
before_script:
  - echo "no tests before script"

script:
  - docker --version # Print docker version for logging
  - docker build -t reverseproxy:v1b ./udagram-reverseproxy
  - docker build -t udagram-api-feed:v1b ./udagram-api-feed
  - docker build -t udagram-api-user:v1b ./udagram-api-user
  - docker build -t udagram-frontend:v3b ./udagram-frontend
  # Tagging
  - docker tag reverseproxy moustafaashraf/reverseproxy:v1a
  - docker tag udagram-api-feed moustafaashraf/udagram-api-feed:v1b
  - docker tag udagram-api-user moustafaashraf/udagram-api-user:v1a
  - docker tag udagram-frontend moustafaashraf/udagram-frontend:v3b

# Tasks to perform after the process is successful
# Formatting the Docker username and password
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push moustafaashraf/reverseproxy:v1a
  - docker push moustafaashraf/udagram-api-feed:v1b
  - docker push moustafaashraf/udagram-api-user:v1a
  - docker push moustafaashraf/udagram-frontend:v3b
