name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image feed
        run: cd udagram-api-feed
        run: docker build -t udagram-api-feed:v1b ./udagram-api-feed
        run: docker tag udagram-api-feed moustafaashraf/udagram-api-feed:v1b
        run: docker push moustafaashraf/udagram-api-feed:v1b
        run: cd ..

      - name: Build the Docker image user
        run: cd udagram-api-user
        run: docker build -t udagram-api-user:v1b ./udagram-api-user
        run: docker tag udagram-api-user moustafaashraf/udagram-api-user:v1a
        run: docker push moustafaashraf/udagram-api-user:v1a
        run: cd ..

      - name: Build the Docker image frontend
        run: cd udagram-frontend
        run: docker build -t udagram-frontend:v3b ./udagram-frontend
        run: docker tag udagram-frontend moustafaashraf/udagram-frontend:v3b
        run: docker push moustafaashraf/udagram-frontend:v3b
        run: cd ..

      - name: Build the Docker image reverseproxy
        run: cd udagram-reverseproxy
        run: docker build -t reverseproxy:v1b ./udagram-reverseproxy
        run: docker tag reverseproxy moustafaashraf/reverseproxy:v1a
        run: docker push moustafaashraf/reverseproxy:v1a
        run: cd ..
