apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
  labels:
    app: api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-feed
  template:
    metadata:
      labels:
        app: api-feed
    spec:
      containers:
        - name: api-feed
          image: moustafaashraf/udagram-api-feed:v1b
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "300m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
