apiVersion: v1
kind: Service
metadata:
  name: api-feed
  labels:
    app: api-feed
specs:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-feed
