# # Create aws-secret.yaml file to store your AWS login credentials.
# # Replace ___INSERT_AWS_CREDENTIALS_FILE__BASE64____ with the Base64 encoded credentials
# # (not the regular username/password).
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: env-config
# data:
#   POSTGRES_HOST: postgres.c5wpoymggfyb.us-east-1.rds.amazonaws.com
#   POSTGRES_DB: postgres
#   AWS_BUCKET: rn:aws:s3:::bucket-2110853-0
#   AWS_REGION: us-east-2
#   JWT_SECRET: testing
#   AWS_PROFILE: default
#   URL: http://localhost:8100

apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBUVNWUkNLVFpZMlQ1T1k1Mgphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSBoZ2JaVGphMkR0MjRkdTQ0ckRVMFMvaHY3eVQwRnE2OGRSNXVPaG5p
