apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
specs:
  ports:
    name: "8100"
    port: 8100
    port: 8100
    targetPort: 8100
    protocol: TCP
  selector:
      app: frontend
