apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
specs:
  replicas: 1
  selector:
    matchlabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        name: frontend
        image: moustafaashraf/udagram-frontend:local
        imagePullPolicy: Always
