apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
specs:
  replicas: 1
  selector:
    matchlabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        name: frontend
        image: moustafaashraf/udagram-frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        envForm:
          secretRef:
            name: env-secret
          configMapRef:
            name: env-config
          secretRef:
            name: aws-secret
        ports:
          containerPort: 8080
